FROM centos:7

RUN yum install -y python3 python3-pip && \
    pip3 install pandas psycopg2-binary

COPY sample.csv /app/sample.csv
COPY ingest_data.py /app/ingest_data.py

WORKDIR /app

CMD ["python3", "ingest_data.py"]
