name: Full Stack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Build and start services
      run: |
        docker compose up -d --build
        echo "⏳ Esperando 30s que la API arranque..."
        sleep 30

    - name: Install test dependencies
      run: |
        pip install pytest requests

    - name: Run tests
      run: |
        pytest tests/

    - name: Tear down services
      if: always()
      run: docker compose down
