name: Full Stack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Build and run all services
      run: |
        docker-compose up -d --build
        echo "Esperando que la API esté disponible..."
        sleep 30  # esperar para asegurar que la API arranque

    - name: Install test dependencies
      run: |
        pip install pytest requests

    - name: Run tests
      run: |
        pytest tests/

    - name: Shutdown
      if: always()
      run: docker-compose down
