name: Full Stack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and start all services
      run: |
        docker compose up -d --build

    - name: Wait for API container to be ready
      run: |
        TIMEOUT=60
        until docker compose ps api | grep -q "Up"; do
          echo "Esperando que el contenedor API esté funcionando"
          sleep 2
          TIMEOUT=$((TIMEOUT - 2))
          if [ $TIMEOUT -le 0 ]; then
            echo "!!Timeout: el contenedor API no arrancó a tiempo"
            docker compose logs api
            exit 1
          fi
        done
        echo "EUREKA!! Contenedor API está activo"

    - name: Run tests inside API container
      run: |
        docker compose exec api pytest tests/

    - name: Tear down services
      if: always()
      run: docker compose down
